export const CANDIDATE_DELETE_SUCCESS = 'CANDIDATE_DELETE_SUCCESS'
export const CANDIDATE_DELETE_FAIL = 'CANDIDATE_DELETE_FAIL'
export const CANDIDATE_DELETE_REQUEST = 'CANDIDATE_DELETE_REQUEST'
export const CANDIDATE_DELETE_RESET = 'CANDIDATE_DELETE_RESET'

export const CANDIDATES_FETCH_SUCCESS = 'CANDIDATES_FETCH_SUCCESS'
export const CANDIDATES_FETCH_FAIL = 'CANDIDATES_FETCH_FAIL'
export const CANDIDATES_FETCH_REQUEST = 'CANDIDATES_FETCH_REQUEST'
export const CANDIDATES_FETCH_RESET = 'CANDIDATES_FETCH_RESET'

export const APPROVE_CANDIDATE_SUCCESS = 'APPROVE_CANDIDATE_SUCCESS'
export const APPROVE_CANDIDATE_FAIL = 'APPROVE_CANDIDATE_FAIL'
export const APPROVE_CANDIDATE_REQUEST = 'APPROVE_CANDIDATE_REQUEST'
export const APPROVE_CANDIDATE_RESET = 'APPROVE_CANDIDATE_RESET'