export const COMPANY_DELETE_SUCCESS = 'COMPANY_DELETE_SUCCESS'
export const COMPANY_DELETE_FAIL = 'COMPANY_DELETE_FAIL'
export const COMPANY_DELETE_REQUEST = 'COMPANY_DELETE_REQUEST'
export const COMPANY_DELETE_RESET = 'COMPANY_DELETE_RESET'

export const COMPANIES_FETCH_SUCCESS = 'COMPANIES_FETCH_SUCCESS'
export const COMPANIES_FETCH_FAIL = 'COMPANIES_FETCH_FAIL'
export const COMPANIES_FETCH_REQUEST = 'COMPANIES_FETCH_REQUEST'
export const COMPANIES_FETCH_RESET = 'COMPANIES_FETCH_RESET'

export const COMPANY_FETCH_SUCCESS = 'COMPANY_FETCH_SUCCESS'
export const COMPANY_FETCH_FAIL = 'COMPANY_FETCH_FAIL'
export const COMPANY_FETCH_REQUEST = 'COMPANY_FETCH_REQUEST'

export const COMPANY_POST_SUCCESS = 'COMPANY_POST_SUCCESS'
export const COMPANY_POST_FAIL = 'COMPANY_POST_FAIL'
export const COMPANY_POST_REQUEST = 'COMPANY_POST_REQUEST'
export const COMPANY_POST_RESET = 'COMPANY_POST_RESET'

export const COMPANY_UPDATE_SUCCESS = 'COMPANY_UPDATE_SUCCESS'
export const COMPANY_UPDATE_FAIL = 'COMPANY_UPDATE_FAIL'
export const COMPANY_UPDATE_REQUEST = 'COMPANY_UPDATE_REQUEST'
export const COMPANY_UPDATE_RESET = 'COMPANY_UPDATE_RESET'

export const MEMBER_VALIDATION_FETCH_REQUEST = 'MEMBER_VALIDATION_FETCH_REQUEST'
export const MEMBER_VALIDATION_FETCH_SUCCESS = 'MEMBER_VALIDATION_FETCH_SUCCESS'
export const MEMBER_VALIDATION_FETCH_FAIL = 'MEMBER_VALIDATION_FETCH_FAIL'