export const SEND_EMAIL_REQUEST = 'SEND_EMAIL_REQUEST'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAIL = 'SEND_EMAIL_FAIL'

export const NOTIFY_EMAIL_REQUEST = 'NOTIFY_EMAIL_REQUEST'
export const NOTIFY_EMAIL_SUCCESS = 'NOTIFY_EMAIL_SUCCESS'
export const NOTIFY_EMAIL_FAIL = 'NOTIFY_EMAIL_FAIL'