export const EVENTS_FETCH_SUCCESS = 'EVENTS_FETCH_SUCCESS'
export const EVENTS_FETCH_FAIL = 'EVENTS_FETCH_FAIL'
export const EVENTS_FETCH_REQUEST = 'EVENTS_FETCH_REQUEST'

export const EVENT_DELETE_SUCCESS = "EVENT_DELETE_SUCCESS"
export const EVENT_DELETE_REQUEST = "EVENT_DELETE_REQUEST"
export const EVENT_DELETE_FAIL = "EVENT_DELETE_FAIL"
