export const EXPORT_USER_FETCH_SUCCESS = 'EXPORT_USER_FETCH_SUCCESS'
export const EXPORT_USER_FETCH_FAIL = 'EXPORT_USER_FETCH_FAIL'
export const EXPORT_USER_FETCH_REQUEST = 'EXPORT_USER_FETCH_REQUEST'
export const EXPORT_USER_FETCH_RESET = 'EXPORT_USER_FETCH_RESET'

export const EXPORT_COMPANY_FETCH_SUCCESS = "EXPORT_COMPANY_FETCH_SUCCESS"
export const EXPORT_COMPANY_FETCH_REQUEST = "EXPORT_COMPANY_FETCH_REQUEST"
export const EXPORT_COMPANY_FETCH_FAIL = "EXPORT_COMPANY_FETCH_FAIL"
export const EXPORT_COMPANY_FETCH_RESET = "EXPORT_COMPANY_FETCH_RESET"

export const EXPORT_CANDIDATE_FETCH_SUCCESS = "EXPORT_CANDIDATE_FETCH_SUCCESS"
export const EXPORT_CANDIDATE_FETCH_REQUEST = "EXPORT_CANDIDATE_FETCH_REQUEST"
export const EXPORT_CANDIDATE_FETCH_FAIL = "EXPORT_CANDIDATE_FETCH_FAIL"
export const EXPORT_CANDIDATE_FETCH_RESET = "EXPORT_CANDIDATE_FETCH_RESET"