export const MEMBER_GROUPS_FETCH_SUCCESS = 'MEMBER_GROUPS_FETCH_SUCCESS'
export const MEMBER_GROUPS_FETCH_FAIL = 'MEMBER_GROUPS_FETCH_FAIL'
export const MEMBER_GROUPS_FETCH_REQUEST = 'MEMBER_GROUPS_FETCH_REQUEST'

export const MEMBER_GROUP_DELETE_REQUEST = 'MEMBER_GROUP_DELETE_REQUEST'
export const MEMBER_GROUP_DELETE_SUCCESS = 'MEMBER_GROUP_DELETE_SUCCESS'
export const MEMBER_GROUP_DELETE_FAIL = 'MEMBER_GROUP_DELETE_FAIL'

export const GROUPS_FETCH_SUCCESS = 'GROUPS_FETCH_SUCCESS'
export const GROUPS_FETCH_FAIL = 'GROUPS_FETCH_FAIL'
export const GROUPS_FETCH_REQUEST = 'GROUPS_FETCH_REQUEST'

export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST'
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS'
export const GROUP_DELETE_FAIL = 'GROUP_DELETE_FAIL'

export const GROUP_FETCH_SUCCESS = 'GROUP_FETCH_SUCCESS'
export const GROUP_FETCH_FAIL = 'GROUP_FETCH_FAIL'
export const GROUP_FETCH_REQUEST = 'GROUP_FETCH_REQUEST'

export const GROUP_MEMBERS_FETCH_REQUEST = 'GROUP_MEMBERS_FETCH_REQUEST'
export const GROUP_MEMBERS_FETCH_SUCCESS = 'GROUP_MEMBERS_FETCH_SUCCESS'
export const GROUP_MEMBERS_FETCH_FAIL = 'GROUP_MEMBERS_FETCH_FAIL'