export const MEMBER_GROUPS_FETCH_SUCCESS = 'MEMBER_GROUPS_FETCH_SUCCESS'
export const MEMBER_GROUPS_FETCH_FAIL = 'MEMBER_GROUPS_FETCH_FAIL'
export const MEMBER_GROUPS_FETCH_REQUEST = 'MEMBER_GROUPS_FETCH_REQUEST'
export const MEMBER_GROUPS_FETCH_RESET = 'MEMBER_GROUPS_FETCH_RESET'

export const GROUPS_FETCH_SUCCESS = 'GROUPS_FETCH_SUCCESS'
export const GROUPS_FETCH_FAIL = 'GROUPS_FETCH_FAIL'
export const GROUPS_FETCH_REQUEST = 'GROUPS_FETCH_REQUEST'
export const GROUPS_FETCH_RESET = 'GROUPS_FETCH_RESET'

export const GROUP_DELETE_REQUEST = 'GROUP_DELETE_REQUEST'
export const GROUP_DELETE_SUCCESS = 'GROUP_DELETE_SUCCESS'
export const GROUP_DELETE_FAIL = 'GROUP_DELETE_FAIL'

export const GROUP_FETCH_SUCCESS = 'GROUP_FETCH_SUCCESS'
export const GROUP_FETCH_FAIL = 'GROUP_FETCH_FAIL'
export const GROUP_FETCH_REQUEST = 'GROUP_FETCH_REQUEST'
export const GROUP_FETCH_RESET = 'GROUP_FETCH_RESET'

export const GROUP_MEMBERS_FETCH_REQUEST = 'GROUP_MEMBERS_FETCH_REQUEST'
export const GROUP_MEMBERS_FETCH_SUCCESS = 'GROUP_MEMBERS_FETCH_SUCCESS'
export const GROUP_MEMBERS_FETCH_FAIL = 'GROUP_MEMBERS_FETCH_FAIL'
export const GROUP_MEMBERS_FETCH_RESET = 'GROUP_MEMBERS_FETCH_RESET'

export const GROUP_POST_REQUEST = 'GROUP_POST_REQUEST'
export const GROUP_POST_SUCCESS = 'GROUP_POST_SUCCESS'
export const GROUP_POST_FAIL = 'GROUP_POST_FAIL'
export const GROUP_POST_RESET = 'GROUP_POST_RESET'