export const MEMBER_LOGIN_REQUEST = 'MEMBER_LOGIN_REQUEST'
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS'
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL'
export const MEMBER_LOGOUT = 'MEMBER_LOGOUT'

export const MEMBER_FETCH_SUCCESS = 'MEMBER_FETCH_SUCCESS'
export const MEMBER_FETCH_FAIL = 'MEMBER_FETCH_FAIL'
export const MEMBER_FETCH_REQUEST = 'MEMBER_FETCH_REQUEST'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL'
export const CHANGE_PASSWORD_RESET = 'CHANGE_PASSWORD_RESET'

export const CHANGE_PASSWORD_REQUEST_REQUEST = 'CHANGE_PASSWORD_REQUEST_REQUEST'
export const CHANGE_PASSWORD_REQUEST_SUCCESS = 'CHANGE_PASSWORD_REQUEST_SUCCESS'
export const CHANGE_PASSWORD_REQUEST_FAIL = 'CHANGE_PASSWORD_REQUEST_FAIL'
export const CHANGE_PASSWORD_REQUEST_RESET = 'CHANGE_PASSWORD_REQUEST_RESET'

export const CHANGE_CREDENTIALS_REQUEST = 'CHANGE_CREDENTIALS_REQUEST'
export const CHANGE_CREDENTIALS_SUCCESS = 'CHANGE_CREDENTIALS_SUCCESS'
export const CHANGE_CREDENTIALS_FAIL = 'CHANGE_CREDENTIALS_FAIL'
export const CHANGE_CREDENTIALS_RESET = 'CHANGE_CREDENTIALS_RESET'

