export const MEMBER_LOGIN_REQUEST = 'MEMBER_LOGIN_REQUEST'
export const MEMBER_LOGIN_SUCCESS = 'MEMBER_LOGIN_SUCCESS'
export const MEMBER_LOGIN_FAIL = 'MEMBER_LOGIN_FAIL'
export const MEMBER_LOGOUT = 'MEMBER_LOGOUT'

export const MEMBER_FETCH_SUCCESS = 'MEMBER_FETCH_SUCCESS'
export const MEMBER_FETCH_FAIL = 'MEMBER_FETCH_FAIL'
export const MEMBER_FETCH_REQUEST = 'MEMBER_FETCH_REQUEST'