
export const QUOTAS_FETCH_SUCCESS = 'QUOTAS_FETCH_SUCCESS'
export const QUOTAS_FETCH_FAIL = 'QUOTAS_FETCH_FAIL'
export const QUOTAS_FETCH_REQUEST = 'QUOTAS_FETCH_REQUEST'

export const QUOTA_UPDATE_SUCCESS = 'QUOTA_UPDATE_SUCCESS'
export const QUOTA_UPDATE_FAIL = 'QUOTA_UPDATE_FAIL'
export const QUOTA_UPDATE_REQUEST = 'QUOTA_UPDATE_REQUEST'

export const MEMBER_QUOTAS_FETCH_SUCCESS = 'MEMBER_QUOTAS_FETCH_SUCCESS'
export const MEMBER_QUOTAS_FETCH_FAIL = 'MEMBER_QUOTAS_FETCH_FAIL'
export const MEMBER_QUOTAS_FETCH_REQUEST = 'MEMBER_QUOTAS_FETCH_REQUEST'