export const QUOTAS_FETCH_SUCCESS = 'QUOTAS_FETCH_SUCCESS'
export const QUOTAS_FETCH_FAIL = 'QUOTAS_FETCH_FAIL'
export const QUOTAS_FETCH_REQUEST = 'QUOTAS_FETCH_REQUEST'
export const QUOTAS_FETCH_RESET = 'QUOTAS_FETCH_RESET'

export const QUOTA_UPDATE_SUCCESS = 'QUOTA_UPDATE_SUCCESS'
export const QUOTA_UPDATE_FAIL = 'QUOTA_UPDATE_FAIL'
export const QUOTA_UPDATE_REQUEST = 'QUOTA_UPDATE_REQUEST'
export const QUOTA_UPDATE_RESET = 'QUOTA_UPDATE_RESET'

export const MEMBER_QUOTAS_FETCH_SUCCESS = 'MEMBER_QUOTAS_FETCH_SUCCESS'
export const MEMBER_QUOTAS_FETCH_FAIL = 'MEMBER_QUOTAS_FETCH_FAIL'
export const MEMBER_QUOTAS_FETCH_REQUEST = 'MEMBER_QUOTAS_FETCH_REQUEST'
export const MEMBER_QUOTAS_FETCH_RESET = 'MEMBER_QUOTAS_FETCH_RESET'

export const QUOTA_CREATE_SUCCESS = 'QUOTA_CREATE_SUCCESS'
export const QUOTA_CREATE_FAIL = 'QUOTA_CREATE_FAIL'
export const QUOTA_CREATE_REQUEST = 'QUOTA_CREATE_REQUEST'
export const QUOTA_CREATE_RESET = 'QUOTA_CREATE_RESET'

export const QUOTA_DELETE_SUCCESS = 'QUOTA_DELETE_SUCCESS'
export const QUOTA_DELETE_FAIL = 'QUOTA_DELETE_FAIL'
export const QUOTA_DELETE_REQUEST = 'QUOTA_DELETE_REQUEST'
export const QUOTA_DELETE_RESET = 'QUOTA_DELETE_RESET'

