
export const QUOTAS_FETCH_SUCCESS = 'QUOTAS_FETCH_SUCCESS'
export const QUOTAS_FETCH_FAIL = 'QUOTAS_FETCH_FAIL'
export const QUOTAS_FETCH_REQUEST = 'QUOTAS_FETCH_REQUEST'

export const QUOTA_UPDATE_SUCCESS = 'QUOTA_DELETE_SUCCESS'
export const QUOTA_UPDATE_FAIL = 'QUOTA_DELETE_FAIL'
export const QUOTA_UPDATE_REQUEST = 'QUOTA_DELETE_REQUEST'