export const SPORTS_FETCH_SUCCESS = 'SPORTS_FETCH_SUCCESS'
export const SPORTS_FETCH_FAIL = 'SPORTS_FETCH_FAIL'
export const SPORTS_FETCH_REQUEST = 'SPORTS_FETCH_REQUEST'
export const SPORTS_FETCH_RESET = 'SPORTS_FETCH_RESET'

export const SPORT_DELETE_SUCCESS = 'SPORT_DELETE_SUCCESS'
export const SPORT_DELETE_FAIL = 'SPORT_DELETE_FAIL'
export const SPORT_DELETE_REQUEST = 'SPORT_DELETE_REQUEST'
export const SPORT_DELETE_RESET = 'SPORT_DELETE_RESET'

export const SPORT_CREATE_SUCCESS = 'SPORT_CREATE_SUCCESS'
export const SPORT_CREATE_FAIL = 'SPORT_CREATE_FAIL'
export const SPORT_CREATE_REQUEST = 'SPORT_CREATE_REQUEST'
export const SPORT_CREATE_RESET = 'SPORT_CREATE_RESET'

export const SPORT_UPDATE_SUCCESS = 'SPORT_UPDATE_SUCCESS'
export const SPORT_UPDATE_FAIL = 'SPORT_UPDATE_FAIL'
export const SPORT_UPDATE_REQUEST = 'SPORT_UPDATE_REQUEST'
export const SPORT_UPDATE_RESET = 'SPORT_UPDATE_RESET'

export const USER_SPORT_TYPES_FETCH_REQUEST = 'USER_SPORT_TYPES_FETCH_REQUEST'
export const USER_SPORT_TYPES_FETCH_SUCCESS = 'USER_SPORT_TYPES_FETCH_SUCCESS'
export const USER_SPORT_TYPES_FETCH_FAIL = 'USER_SPORT_TYPES_FETCH_FAIL'
export const USER_SPORT_TYPES_FETCH_RESET = 'USER_SPORT_TYPES_FETCH_RESET'