
export const SPORTS_FETCH_SUCCESS = 'SPORTS_FETCH_SUCCESS'
export const SPORTS_FETCH_FAIL = 'SPORTS_FETCH_FAIL'
export const SPORTS_FETCH_REQUEST = 'SPORTS_FETCH_REQUEST'

export const SPORT_DELETE_SUCCESS = 'SPORT_DELETE_SUCCESS'
export const SPORT_DELETE_FAIL = 'SPORT_DELETE_FAIL'
export const SPORT_DELETE_REQUEST = 'SPORT_DELETE_REQUEST'