export const STATISTICS_FETCH_SUCCESS = 'STATISTICS_FETCH_SUCCESS'
export const STATISTICS_FETCH_FAIL = 'STATISTICS_FETCH_FAIL'
export const STATISTICS_FETCH_REQUEST = 'STATISTICS_FETCH_REQUEST'
export const STATISTICS_FETCH_RESET = 'STATISTICS_FETCH_RESET'

