export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'

export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
export const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL'
export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST'

export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'


export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'

export const USER_SPORTS_FETCH_SUCCESS = "USER_SPORTS_FETCH_SUCCESS"
export const USER_SPORTS_FETCH_FAIL = "USER_SPORTS_FETCH_FAIL"
export const USER_SPORTS_FETCH_REQUEST = "USER_SPORTS_FETCH_REQUEST"

