export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'
export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'

export const USERS_FETCH_SUCCESS = 'USERS_FETCH_SUCCESS'
export const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL'
export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST'

export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'
export const USER_FETCH_FAIL = 'USER_FETCH_FAIL'
export const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST'

export const SPORTS_FETCH_SUCCESS = 'SPORTS_FETCH_SUCCESS'
export const SPORTS_FETCH_FAIL = 'SPORTS_FETCH_FAIL'
export const SPORTS_FETCH_REQUEST = 'SPORTS_FETCH_REQUEST'

export const SPORT_DELETE_SUCCESS = 'SPORT_DELETE_SUCCESS'
export const SPORT_DELETE_FAIL = 'SPORT_DELETE_FAIL'
export const SPORT_DELETE_REQUEST = 'SPORT_DELETE_REQUEST'

export const QUOTAS_FETCH_SUCCESS = 'QUOTAS_FETCH_SUCCESS'
export const QUOTAS_FETCH_FAIL = 'QUOTAS_FETCH_FAIL'
export const QUOTAS_FETCH_REQUEST = 'QUOTAS_FETCH_REQUEST'

export const QUOTA_UPDATE_SUCCESS = 'QUOTA_DELETE_SUCCESS'
export const QUOTA_UPDATE_FAIL = 'QUOTA_DELETE_FAIL'
export const QUOTA_UPDATE_REQUEST = 'QUOTA_DELETE_REQUEST'